# Generated by Django 4.2.5 on 2023-10-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TTS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("newari_text", models.CharField(max_length=200)),
                ("speech_url", models.CharField(max_length=200)),
            ],
        ),
    ]
